version: '3.2'
services:

  tomcat:
    image: reactome_tomcat_alt
    container_name: tomcat-server
    hostname: tomcat-server
    build:
      context: ./tomcat
      dockerfile: tomcat.alt.dockerfile
    depends_on:
      - mysql-for-tomcat
      - joomla-sites
      - neo4j-db
      - solr
    links:
      - mysql-for-tomcat
      - joomla-sites
      - neo4j-db
    entrypoint: bash -c "ls -lht /certs && /wait-for.sh neo4j-db:7687 -t 500 && /wait-for.sh neo4j-db:7474 -t 500 && /wait-for.sh solr-for-reactome:8983 -t 500 && /wait-for.sh mysql-for-tomcat:3306 -t 500 && /wait-for.sh joomla-sites:80 -t 500 && { echo yes | keytool -v -import -file /certs/server.crt -alias joomla-sites -keystore cacerts.jks -keypass changeit -storepass changeit || ( keytool -v -delete -alias joomla-sites -keystore  cacerts.jks -storepass changeit && echo yes | keytool -v -import -file /certs/server.crt -alias joomla-sites -keystore cacerts.jks -keypass changeit -storepass changeit ) ; } && catalina.sh run"
    volumes:
      - ./java-application-builder/downloads/interactors.db:/interactors.db
      - ./java-application-builder/downloads/analysis.bin:/analysis.bin
      - ./java-application-builder/downloads/diagrams_and_fireworks/fireworks:/usr/local/tomcat/webapps/download/current/fireworks
      - ./java-application-builder/downloads/diagrams_and_fireworks/diagram:/usr/local/tomcat/webapps/download/current/diagram
      - ./wait-for.sh:/wait-for.sh
      - ./tomcat/rewrite.config:/usr/local/tomcat/conf/Catalina/localhost/rewrite.config
      - ./tomcat/tomcat-users.xml:/usr/local/tomcat/conf/tomcat-users.xml
      - ./tomcat/tomcat-server.xml:/usr/local/tomcat/conf/server.xml
      - ./tomcat/tomcat-manager.xml:/usr/local/tomcat/conf/Catalina/localhost/manager.xml
      - ./tomcat/analysis-service/results:/usr/local/AnalysisService/analysis-results
      - ./tomcat/analysis-service/reports:/usr/local/AnalysisService/analysis-reports
      - ./tomcat/logging.properties:/usr/local/tomcat/conf/logging.properties
      - ./logs/applications/AnalysisService:/usr/local/AnalysisService/log
      - ./logs/applications/ContentService:/usr/local/search/log/content-service
      - ./logs/applications/DataContent:/usr/local/search/log/data-content
      - ./logs/tomcat/:/usr/local/tomcat/logs/ #to save logs inside host directory of tomcat/logs/
      - ./certificates:/certs
    env_file:
      - tomcat.env
    ports:
      - 8082:8080

  solr:
    image: solr:6.6.0
    container_name: solr-for-reactome
    hostname: solr-for-reactome
    ports:
      - "8983:8983"
    volumes:
      - ./solr/data/solr_data:/opt/solr/server/solr/mycores
      - ./solr/solrconfig.xml:/opt/solr/server/solr/mycores/reactome/conf/solrconfig.xml
      - ./logs/solr/:/opt/solr/server/logs/
      - ./solr/solr-security.json:/opt/solr/server/solr/security.json:rw
    entrypoint:
      - docker-entrypoint.sh
      - solr-precreate
      - reactome

  neo4j-db:
    image: reactome/reactome-neo4j:R-999
    build:
      context: ./neo4j
      dockerfile: neo4j_stand-alone.dockerfile
    container_name: neo4j-db
    hostname: neo4j-db
    volumes:
      # - ./neo4j/data:/var/lib/neo4j/data/databases
      - ./logs/neo4j/:/var/lib/neo4j/logs/
    ports:
      - 7474:7474
      - 7687:7687

  mysql-for-tomcat:
    image: mysql
    hostname: mysql-for-tomcat
    container_name: mysql-for-tomcat
    env_file:
      - tomcat.env
    volumes:
      - ./mysql/tomcat_data/:/docker-entrypoint-initdb.d
      - ./mysql/init.sh:/init.sh
      - ./logs/mysql/tomcat:/var/log/mysql
      - mysql-for-tomcat-log:/backup
    command: bash -c "/init.sh && exec /entrypoint.sh mysqld"

  mysql-for-joomla:
    image: mysql
    hostname: mysql-for-joomla
    container_name: mysql-for-joomla
    env_file:
      - joomla.env
    volumes:
      - ./joomla/Website/database/:/docker-entrypoint-initdb.d
      - ./mysql/init.sh:/init.sh
      - ./logs/mysql/joomla:/var/log/mysql
      - mysql-for-joomla-log:/backup
    command: bash -c "/init.sh && exec /entrypoint.sh mysqld"


  joomla-sites:
    hostname: joomla-sites
    image: joomla:4.8.1_for_reactome
    build:
      context: ./joomla
      dockerfile: joomla.dockerfile
    container_name: joomla-sites
    links:
      - mysql-for-joomla
    depends_on:
      - mysql-for-joomla
    env_file:
      - joomla.env
    ports:
      - 80:80
      - 443:443
    entrypoint: bash -c "/wait-for.sh mysql-for-joomla:3306 -t 360  -- cp /etc/apache2/ssl/* /certs/ && /usr/local/bin/docker-php-entrypoint apache2-foreground"
    volumes:
      - ./wait-for.sh:/wait-for.sh
      - ./joomla/000-default.conf:/etc/apache2/sites-enabled/000-default.conf
      - ./joomla/000-default-ssl.conf:/etc/apache2/sites-enabled/default-ssl.conf
      - ./joomla/configuration.php:/var/www/html/configuration.php
      - ./certificates:/certs
      - ./joomla/php.ini:/usr/local/etc/php/php.ini
      - ./joomla/Secrets.pm:/var/www/html/cgi-modules/GKB/Secrets.pm
      - ./joomla/Config.pm:/var/www/html/cgi-modules/GKB/Config.pm
      - ./tmp_files:/var/www/html/cgi-tmp
      - ./joomla/cgi-modules/GKB/FrontPage3.pm:/var/www/html/cgi-modules/GKB/FrontPage3.pm
volumes:
  mysql-for-joomla-log:
  mysql-for-tomcat-log:
