version: '3'
services:

  tomcat:
    image: tomcat:7.0
    container_name: tomcat-server
    depends_on:
      - mysql-database
    volumes:
      - ./release/modules/GKB/:/usr/local/gkb/modules/GKB
      - ./release/scripts/:/usr/local/bin/perl/scripts
    env_file:
      - .env
    ports:
      - 8082:8080

  apache-server:
    image: httpd:2.4
    container_name: apache-server
    volumes:
      - ./release/modules/GKB/:/usr/local/gkb/modules/GKB
      - ./release/scripts/:/usr/local/bin/perl/scripts

  mysql-database:
    image: mysql
    container_name: mysql-database
    volumes:
      - ./mysql/docker-entrypoint-initdb.d/:/docker-entrypoint-initdb.d
    env_file:
      - .env
    ports:
      - 3306:3306

  wordpress-sites:
    image: wordpress
    container_name: wordpress-sites
    links:
      - mysql-database
    depends_on:
      - mysql-database
      - apache-server
      - tomcat
    env_file:
      - .env
    ports:
      - 8080:80
    entrypoint:
      - /wait-for.sh
      - mysql-database:3306
      - -t
      - "90"
      - --
      - /usr/local/bin/docker-entrypoint.sh
      - apache2-foreground
    volumes:
      - ./wait-for.sh:/wait-for.sh
      - ./release/website/html/wordpress/wp-content/:/var/www/html/wp-content
      - ./release/website/html/wordpress/wp-includes/:/var/www/html/wp-includes
